### ISSUE TITLE
ending an email secure caused a crash

### ISSUE THREAD

**Issue by siobhanellis** [potrudeau/homebridge-messenger#15]
[11/17/2020, 1:36:45 PM] [Messenger] Washing Machine has finished : Message sent to sxxxxxxxxs@hotmail.com
[11/17/2020, 1:36:46 PM] Error: Error: 4358954496:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at /usr/local/lib/node_modules/homebridge-messenger/lib/email.js:66:17
    at /usr/local/lib/node_modules/homebridge-messenger/node_modules/nodemailer/lib/mailer/index.js:226:21
    at SMTPConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-messenger/node_modules/nodemailer/lib/smtp-transport/index.js:175:24)
    at Object.onceWrapper (events.js:422:26)
    at SMTPConnection.emit (events.js:315:20)
    at SMTPConnection._onError (/usr/local/lib/node_modules/homebridge-messenger/node_modules/nodemailer/lib/smtp-connection/index.js:764:14)
    at TLSSocket.SMTPConnection._onSocketError (/usr/local/lib/node_modules/homebridge-messenger/node_modules/nodemailer/lib/smtp-connection/index.js:190:45)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

`{
            "name": "Messenger",
            "services": {
                "email": {
                    "recipient": "sxxxxxxxxs@hotmail.com",
                    "smtpServer": "smtp.office365.com",
                    "smtpPort": 587,
                    "smtpSecure": false,
                    "smtpUsername": "siobhanellis@hotmail.com",
                    "smtpPassword": "my correct password"
                }
            },
            "messages": [
                {
                    "name": "Dryer Has finished",
                    "type": "email",
                    "text": "The Dryer seems to have Finished",
                    "priority": 0,
                    "sound": "pushover"
                },
                {
                    "name": "Washing Machine has finished",
                    "type": "email",
                    "text": "The Washing Machine seems to have Finished",
                    "priority": 0,
                    "sound": "pushover"
                }
            ],
            "accessory": "HomebridgeMessenger"
        }`

When I turned secure off, everything is OK.

**Comment by Ghitafjorback** [comment]
I get this exact same error. Mine did not help just by turning off the secure. Is yours still working?

**Comment by potrudeau** [comment]
This is bug. I will look into this.

**Comment by potrudeau** [comment]
@Ghitafjorback : Were you able to make it work with secure=false ? It appears to be a problem with your server. I also have the same problem on my setups.

**Comment by Ghitafjorback** [comment]
No, I did not get it to work. Unfortunately.

**Comment by potrudeau** [comment]
@Ghitafjorback and @siobhanellis  : Solved in new version 0.0.7. It's published and available now.
