### ISSUE TITLE
uncaught exception 

### ISSUE THREAD

**Issue by NicholasB60** [potrudeau/homebridge-messenger#22]
This exception caused Homebridge to crash

[2/13/2021, 3:42:11 PM] [Messenger] Garage door - Open : Message sent to xxxxxx.xxxxxx@me.com
[2/13/2021, 3:42:11 PM] [Messenger] Main Switch status : true
[2/13/2021, 3:42:13 PM] [zigbee] Garage Door Sensor: set homekit contact from 1 to 0
[2/13/2021, 3:42:21 PM] Error: Error: Client network socket disconnected before secure TLS connection was established
    at /usr/local/lib/node_modules/homebridge-messenger/lib/email.js:73:17
    at /usr/local/lib/node_modules/homebridge-messenger/node_modules/nodemailer/lib/mailer/index.js:226:21
    at SMTPConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-messenger/node_modules/nodemailer/lib/smtp-transport/index.js:175:24)
    at Object.onceWrapper (events.js:422:26)
    at SMTPConnection.emit (events.js:315:20)
    at SMTPConnection._onError (/usr/local/lib/node_modules/homebridge-messenger/node_modules/nodemailer/lib/smtp-connection/index.js:764:14)
    at TLSSocket.SMTPConnection._onSocketError (/usr/local/lib/node_modules/homebridge-messenger/node_modules/nodemailer/lib/smtp-connection/index.js:190:45)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[2/13/2021, 3:42:21 PM] Got SIGTERM, shutting down Homebridge...
[2/13/2021, 3:42:26 PM] [zigbee] goodbye

**Comment by potrudeau** [comment]
What version are you using ? And what SMTP server ?

**Comment by NicholasB60** [comment]
> What version are you using ? And what SMTP server ?

v.0.0.8 and smtp.gmail.com port 465
