### ISSUE TITLE
Error: application token is invalid - But it isn't.....

### ISSUE THREAD

**Issue by Loffretto** [potrudeau/homebridge-messenger#24]
Hello,

I get the following Error: 

[24.3.2021, 16:07:06] [Messenger] Fenster offen : Message sent to urxXXXXXXXXXXXXXXXXXX4rt
/usr/local/lib/node_modules/homebridge-messenger/node_modules/pushover-notifications/lib/pushover.js:146
        proxy = url.parse(httpOpts.proxy);
            ^
Error: application token is invalid
    at Pushover.errors (/usr/local/lib/node_modules/homebridge-messenger/node_modules/pushover-notifications/lib/pushover.js:146:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-messenger/node_modules/pushover-notifications/lib/pushover.js:250:12)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[24.3.2021, 16:07:07] [Messenger] Child bridge process ended
[24.3.2021, 16:07:07] [Messenger] Process Ended. Code: 1, Signal: null
[24.3.2021, 16:07:14] [Messenger] Restarting Process...
Initializing HAP-NodeJS v0.9.4...

Can anyone help? I'm using latest Homebridge Version 1.3.4 and tested with messenger Version 0.0.7 & 0.0.8

**Comment by Loffretto** [comment]
I got it....
