### ISSUE TITLE
Homebridge Crash duo to error message - Error: getaddrinfo EAI_AGAIN api.pushover.net

### ISSUE THREAD

**Issue by Baggns** [potrudeau/homebridge-messenger#31]
Hi, could you please check that this don't reboot the homebrige?

Thanks a lot

`[12/1/2021, 1:10:57 PM] Error: Error: getaddrinfo EAI_AGAIN api.pushover.net
    at /usr/lib/node_modules/homebridge-messenger/lib/pushover.js:72:23
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-messenger/node_modules/pushover-notifications/lib/pushover.js:263:7)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[12/1/2021, 1:10:57 PM] Error: Error: getaddrinfo EAI_AGAIN api.pushover.net
    at /usr/lib/node_modules/homebridge-messenger/lib/pushover.js:72:23
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-messenger/node_modules/pushover-notifications/lib/pushover.js:263:7)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[12/1/2021, 1:10:57 PM] Got SIGTERM, shutting down Homebridge...`

**Comment by apfelnutzer** [comment]
I've got the same issue - as soon as I try to send a test notification via Pushover this error occurs:

`[2/13/2022, 7:20:15 PM] Error: Error: getaddrinfo EAI_AGAIN api.pushover.net
    at /homebridge/node_modules/homebridge-messenger/lib/pushover.js:72:23
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-messenger/node_modules/pushover-notifications/lib/pushover.js:263:7)
    at ClientRequest.emit (node:events:520:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

Might be related to the Alpine Linux base image of Homebridge, when running in a Docker container:

> If you're using an image derived from alpine linux, there are [known issues](https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.md) with the musl dns resolver

See [here](https://github.com/nodejs/node/issues/15780#issuecomment-425930255).

@baggns: You could try using the Ubuntu based image of Homebridge instead - see [Docker Hub](https://hub.docker.com/r/oznu/homebridge). I‘ll try it out later…

**Comment by apfelnutzer** [comment]
@Baggns, the Ubuntu image works (`oznu/homebridge:ubuntu`) - the error no longer occurs and notifications are sent via Pushover!

**Comment by potrudeau** [comment]
Solved
