### ISSUE TITLE
Getting New Error

### ISSUE THREAD

**Issue by txcvedvr** [potrudeau/homebridge-messenger#6]
Hi, just updated to latest version. Was working great before and has really nice configuration, functionality.

Now I'm getting this when I try an action.

4/26/2020, 13:40:34] TypeError: Cannot read property 'replace' of undefined
    at new PushOverMessenger (/usr/local/lib/node_modules/homebridge-messenger/lib/pushover.js:16:45)
    at HomebridgeMessenger.<anonymous> (/usr/local/lib/node_modules/homebridge-messenger/index.js:78:27)
    at Characteristic.On.emit (events.js:310:20)
    at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:310:20)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
[4/26/2020, 13:40:34] Got SIGTERM, shutting down Homebridge...
[4/26/2020, 13:40:39] [Config] [HapClient] [192.168.1.139:51748 (0E:5C:34:12:B7:CD)] Failed to set value for Alarm - Downstairs.
[4/26/2020, 13:40:39] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

Any ideas what I did wrong?

**Comment by potrudeau** [comment]
@txcvedvr  : Solved in new version 0.0.6. It's published and available now.

**Comment by txcvedvr** [comment]
Confirmed and working great. Thanks.
